apiVersion: apps/v1
kind: Deployment
metadata:
  name: test-ui
  namespace: test
  labels:
     app: test-ui
spec:
  replicas: 1
  selector:
    matchLabels:
       app: test-ui
  template:
    metadata:
      labels:
         app: test-ui
    spec:
      containers:
      - name: test-ui
        image: registry.forge.orange-labs.fr/fwbn0182/oidc-testing-tool:front
        imagePullPolicy: Always
        resources:
          requests:
            memory: "256Mi"
            cpu: "50m"
          limits:
            memory: "512Mi"
            cpu: "250m"
        ports:
        - containerPort: 80
          
      # Image Pull From GitLab Registry Secret    
      imagePullSecrets:
        - name: regcred

---

apiVersion: v1
kind: Service
metadata:
  name: test-ui-svc
  namespace: test
spec:
  type: LoadBalancer
  selector:
    app: test-ui
  ports:
  - name: http
    nodePort: 30080
    port: 80
    protocol: TCP
    targetPort: 80